version: "3.9"

networks:
  only_db_network:

services:
  db:
    image: postgres:14.5
    restart: always
    user: postgres
    ports:
      - "5438:5432"
    env_file:
      - .env
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - only_db_network
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - only_db_network
volumes:
  db:
    driver: local
